/* ── Product data – real MLB Etsy products ── */

const PRODUCTS = [
  {
    id: 1,
    name: "HARIBO Gummifische „Eukalyptus" – Gastgeschenk",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: "Bestseller",
    rating: 5.0,
    reviews: 128,
    image: "images/prod-haribo-fisch.jpg",
    images: ["images/prod-haribo-fisch.jpg"],
    desc: "HARIBO Gummifische in der 25g-Tüte mit individuell bedrucktem Etikett – dein perfektes Gastgeschenk für Babyparty, Taufe oder Geburtstag. Personalisierung mit Name, Datum und Wunschtext möglich. Verpackt in einer hochwertigen, bedruckten Tüte.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "taufe", "babyparty", "geburtstag"],
    bestseller: true
  },
  {
    id: 2,
    name: "HARIBO Gummifische „Taufe" – Gastgeschenk",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: null,
    rating: 4.9,
    reviews: 87,
    image: "images/prod-haribo-fisch-taufe.jpg",
    images: ["images/prod-haribo-fisch-taufe.jpg"],
    desc: "HARIBO Gummifische zur Taufe – mit personalisiertem Etikett in zarten Taufe-Motiven. Mit Kreuz-Motiv, Name und Datum bedruckt. Ein süßes Dankeschön für deine Gäste.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "taufe"],
    bestseller: false
  },
  {
    id: 3,
    name: "HARIBO Goldbären „Regenbogen Mädchen" – Gastgeschenk",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: "Neu",
    rating: 5.0,
    reviews: 62,
    image: "images/prod-haribo-regenbogen-girl.jpg",
    images: ["images/prod-haribo-regenbogen-girl.jpg"],
    desc: "HARIBO Goldbären in der 25g-Tüte mit buntem Regenbogen-Etikett in Rosa – ideal für eine Babyparty zum Mädchen. Personalisierung mit Name und Datum möglich.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "babyparty"],
    bestseller: true
  },
  {
    id: 4,
    name: "HARIBO Goldbären „Regenbogen Junge" – Gastgeschenk",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: null,
    rating: 4.9,
    reviews: 45,
    image: "images/prod-haribo-regenbogen-boy.jpg",
    images: ["images/prod-haribo-regenbogen-boy.jpg"],
    desc: "HARIBO Goldbären in der 25g-Tüte mit buntem Regenbogen-Etikett in Blau – ideal für eine Babyparty zum Jungen. Personalisierung mit Name und Datum möglich.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "babyparty"],
    bestseller: false
  },
  {
    id: 5,
    name: "HARIBO Gummifische „Wal" – Gastgeschenk",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: null,
    rating: 4.8,
    reviews: 34,
    image: "images/prod-haribo-wal.jpg",
    images: ["images/prod-haribo-wal.jpg"],
    desc: "HARIBO Gummifische mit niedlichem Wal-Etikett – perfekt für Babypartys und Geburtstage. Personalisierung mit Name und Datum möglich.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "babyparty", "geburtstag"],
    bestseller: false
  },
  {
    id: 6,
    name: "HARIBO Gummifische „Arche Noah" – Gastgeschenk",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: null,
    rating: 4.8,
    reviews: 29,
    image: "images/prod-haribo-arche.jpg",
    images: ["images/prod-haribo-arche.jpg"],
    desc: "HARIBO Gummifische mit liebevollem Arche-Noah-Motiv – ein unvergessliches Gastgeschenk zur Taufe oder Kommunion. Mit Personalisierung.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "taufe"],
    bestseller: false
  },
  {
    id: 7,
    name: "Ritter Sport Mini „Welcome Home Baby Girl"",
    cat: "welcome-home",
    catLabel: "Welcome Home",
    price: 4.90,
    oldPrice: null,
    badge: "Exklusiv",
    rating: 5.0,
    reviews: 56,
    image: "images/prod-welcome-home-girl.jpg",
    images: ["images/prod-welcome-home-girl.jpg"],
    desc: "Ritter Sport Mini Schokolade mit individuell bedruckter Banderole „Welcome Home Baby Girl". Das perfekte Geschenk zur Geburt – für Mama, Papa und die ganze Familie. Personalisierung mit Name, Datum und Gewicht.",
    options: { menge: ["1 Stück", "5 Stück", "10 Stück", "20 Stück"] },
    tags: ["welcome-home", "geburt"],
    bestseller: true
  },
  {
    id: 8,
    name: "Ritter Sport Mini „Welcome Home Baby Boy"",
    cat: "welcome-home",
    catLabel: "Welcome Home",
    price: 4.90,
    oldPrice: null,
    badge: "Exklusiv",
    rating: 5.0,
    reviews: 48,
    image: "images/prod-welcome-home-boy.jpg",
    images: ["images/prod-welcome-home-boy.jpg"],
    desc: "Ritter Sport Mini Schokolade mit individuell bedruckter Banderole „Welcome Home Baby Boy". Das perfekte Geschenk zur Geburt – für Mama, Papa und die ganze Familie. Personalisierung mit Name, Datum und Gewicht.",
    options: { menge: ["1 Stück", "5 Stück", "10 Stück", "20 Stück"] },
    tags: ["welcome-home", "geburt"],
    bestseller: true
  },
  {
    id: 9,
    name: "Magnetischer Stundenplan – personalisiert (Rosa)",
    cat: "personalisiert",
    catLabel: "Personalisiert",
    price: 12.90,
    oldPrice: null,
    badge: "Bestseller",
    rating: 5.0,
    reviews: 94,
    image: "images/prod-stundenplan-rosa.jpg",
    images: ["images/prod-stundenplan-rosa.jpg"],
    desc: "Personalisierter magnetischer Stundenplan für die Schule in zartem Rosa. Mit Name des Kindes, Klasse und individuell gestalteten Stundenfächern. Hochwertiger Magnettafel-Druck, wetterfest und langlebig. Format A4.",
    options: { klasse: ["1. Klasse", "2. Klasse", "3. Klasse", "4. Klasse", "5. Klasse", "6. Klasse"] },
    tags: ["personalisiert", "schule"],
    bestseller: true
  },
  {
    id: 10,
    name: "Magnetischer Stundenplan – personalisiert (Blau)",
    cat: "personalisiert",
    catLabel: "Personalisiert",
    price: 12.90,
    oldPrice: null,
    badge: null,
    rating: 4.9,
    reviews: 71,
    image: "images/prod-stundenplan-blau.jpg",
    images: ["images/prod-stundenplan-blau.jpg"],
    desc: "Personalisierter magnetischer Stundenplan für die Schule in kühlem Blau. Mit Name des Kindes, Klasse und individuell gestalteten Stundenfächern. Hochwertiger Magnettafel-Druck, wetterfest und langlebig. Format A4.",
    options: { klasse: ["1. Klasse", "2. Klasse", "3. Klasse", "4. Klasse", "5. Klasse", "6. Klasse"] },
    tags: ["personalisiert", "schule"],
    bestseller: false
  },
  {
    id: 11,
    name: "Mutterpass Hülle – personalisiert",
    cat: "personalisiert",
    catLabel: "Personalisiert",
    price: 8.90,
    oldPrice: null,
    badge: "Bestseller",
    rating: 5.0,
    reviews: 112,
    image: "images/prod-mutterpass.jpg",
    images: ["images/prod-mutterpass.jpg"],
    desc: "Liebevoll gestaltete Mutterpass-Hülle aus hochwertigem Material mit individueller Aufschrift. Mit Name der werdenden Mama, Babyname und Wunschtext personalisierbar. Passgenau für den deutschen Mutterpass. Das ideale Geschenk zur Schwangerschaft.",
    options: { design: ["Floral", "Sterne", "Herzen", "Minimalistisch"] },
    tags: ["personalisiert", "geburt", "schwangerschaft"],
    bestseller: true
  },
  {
    id: 12,
    name: "Messlatte „Baby & Kind" – personalisiert (Rosa)",
    cat: "personalisiert",
    catLabel: "Personalisiert",
    price: 34.90,
    oldPrice: 39.90,
    badge: "Sale",
    rating: 4.9,
    reviews: 38,
    image: "images/prod-messlatte-rosa.jpg",
    images: ["images/prod-messlatte-rosa.jpg"],
    desc: "Personalisierte Holzmesslatte für Kinder in zartem Rosa. Mit Name, Geburtsdatum und liebevollen Baby-Motiven. Aus nachhaltigem Holz gefertigt, mit Aufhängung. Wächst mit dem Kind mit – von Geburt bis 150 cm. Lieferung mit Stift zum Eintragen der Größen.",
    options: { holz: ["Natur Hell", "Natur Dunkel"] },
    tags: ["personalisiert", "geburt"],
    bestseller: false
  },
  {
    id: 13,
    name: "Messlatte „Baby & Kind" – personalisiert (Blau)",
    cat: "personalisiert",
    catLabel: "Personalisiert",
    price: 34.90,
    oldPrice: 39.90,
    badge: "Sale",
    rating: 4.9,
    reviews: 31,
    image: "images/prod-messlatte-blau.jpg",
    images: ["images/prod-messlatte-blau.jpg"],
    desc: "Personalisierte Holzmesslatte für Kinder in zartem Blau. Mit Name, Geburtsdatum und liebevollen Baby-Motiven. Aus nachhaltigem Holz gefertigt, mit Aufhängung. Wächst mit dem Kind mit – von Geburt bis 150 cm. Lieferung mit Stift zum Eintragen der Größen.",
    options: { holz: ["Natur Hell", "Natur Dunkel"] },
    tags: ["personalisiert", "geburt"],
    bestseller: false
  },
  {
    id: 14,
    name: "Gastgeschenk „1. Geburtstag Wal" – Gummifische",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: null,
    rating: 5.0,
    reviews: 42,
    image: "images/prod-geburtstag-wal.jpg",
    images: ["images/prod-geburtstag-wal.jpg"],
    desc: "HARIBO Gummifische mit süßem Wal-Etikett „Ich bin 1!" – das perfekte Gastgeschenk für den 1. Geburtstag. Personalisierung mit Name und Datum möglich.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "geburtstag"],
    bestseller: false
  },
  {
    id: 15,
    name: "Gastgeschenk „Wild One" – 1. Geburtstag",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: null,
    rating: 4.8,
    reviews: 25,
    image: "images/prod-wild-one.jpg",
    images: ["images/prod-wild-one.jpg"],
    desc: "HARIBO Gummitierchen mit trendigen „Wild One"-Etikett – perfekt für den 1. Geburtstag im Dschungel- oder Tierstyle. Personalisierung mit Name und Datum möglich.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "geburtstag"],
    bestseller: false
  },
  {
    id: 16,
    name: "Gastgeschenk „Baby Boy" – Gummifische personalisiert",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: null,
    rating: 4.9,
    reviews: 33,
    image: "images/prod-babyboy.jpg",
    images: ["images/prod-babyboy.jpg"],
    desc: "HARIBO Gummifische mit liebevollem „Baby Boy"-Etikett in Blau – das süße Gastgeschenk für Babyparty oder Taufe zum Jungen. Personalisierung mit Name und Datum möglich.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "babyparty", "taufe"],
    bestseller: false
  },
  {
    id: 17,
    name: "Gastgeschenk „Baby Girl" – Gummifische personalisiert",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.50,
    oldPrice: null,
    badge: null,
    rating: 4.9,
    reviews: 37,
    image: "images/prod-babygirl.jpg",
    images: ["images/prod-babygirl.jpg"],
    desc: "HARIBO Gummifische mit liebevollem „Baby Girl"-Etikett in Rosa – das süße Gastgeschenk für Babyparty oder Taufe zum Mädchen. Personalisierung mit Name und Datum möglich.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "babyparty", "taufe"],
    bestseller: false
  },
  {
    id: 18,
    name: "HARIBO Gummifische „Weiß" – Taufe Gastgeschenk",
    cat: "gastgeschenk",
    catLabel: "Gastgeschenke",
    price: 3.90,
    oldPrice: null,
    badge: null,
    rating: 5.0,
    reviews: 19,
    image: "images/prod-fisch-weiss-1.png",
    images: ["images/prod-fisch-weiss-1.png"],
    desc: "Edle weiße HARIBO Gummifische in der 25g-Tüte mit feinem Taufe-Etikett – für eine stimmungsvolle Tauffeier. Personalisierung mit Name und Datum möglich.",
    options: { menge: ["10 Stück", "20 Stück", "30 Stück", "50 Stück"] },
    tags: ["gastgeschenk", "taufe"],
    bestseller: false
  }
];

const CATEGORIES = [
  { id: "all",          label: "Alle" },
  { id: "gastgeschenk",label: "Gastgeschenke" },
  { id: "welcome-home",label: "Welcome Home" },
  { id: "personalisiert", label: "Personalisiert" }
];

/* Category card images */
const CAT_IMAGES = {
  gastgeschenk:  "images/prod-haribo-fisch.jpg",
  "welcome-home": "images/prod-welcome-home-girl.jpg",
  personalisiert: "images/prod-stundenplan-rosa.jpg"
};
